// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name,
  price_in_centers,
  quantity
)
VALUES ($1, $2, $3)
RETURNING id, name, price_in_centers, quantity, created_at
`

type CreateProductParams struct {
	Name           string `json:"name"`
	PriceInCenters int32  `json:"price_in_centers"`
	Quantity       int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceInCenters, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenters,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const findProductById = `-- name: FindProductById :one
SELECT id, name, price_in_centers, quantity, created_at
FROM products
WHERE id = $1
`

func (q *Queries) FindProductById(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenters,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_centers, quantity, created_at
FROM products
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCenters,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2,
    price_in_centers = $3,
    quantity = $4
WHERE id = $1
RETURNING id, name, price_in_centers, quantity, created_at
`

type UpdateProductParams struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	PriceInCenters int32  `json:"price_in_centers"`
	Quantity       int32  `json:"quantity"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.PriceInCenters,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenters,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
